### ISSUE TITLE
No 1.19.4 Release

### ISSUE THREAD

**Issue by ChecksumDev** [jrbudda/Vivecraft_Spigot_Extensions#100] opened 2023-04-30 17:05 UTC
I noticed the commit for 1.19.4 support and was wondering if it was not ready as its release is not published as of yet.
https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases/tag/1.19r1

**Comment by untuned** [comment] 2023-04-30 20:11
Duplicate of https://github.com/jrbudda/Vivecraft_Spigot_Extensions/issues/99

**Comment by jrbudda** [comment] 2023-04-30 22:25
nobody has reported any bugs so I've uploaded it here to the 1.19 release

**Closed by jrbudda** 2023-04-30 22:25 UTC
